name: SayIt Continuous Integration

on: [push]

permissions:
    contents: read
    checks: write
    id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      
      - name: Compile Java Classes
        run: javac -cp .:lib/*:src src/**/*.java src/*.java -d bin

      - name: Compile Unit Tests
        run: javac -cp .:lib/*:bin:src tests/**/*.java -d bin

      - name: Start Server
        run: |
          java -cp .:./lib/*:bin Server &
          sleep 5 &&
          java -jar lib/junit-platform-console-standalone-1.9.3.jar -cp lib/json-20230227.jar:bin --scan-class-path
